#    Copyright 2026 Genesis Corporation.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
"""Authentication methods for GrafanaInstance.

Each auth kind knows how to configure Grafana authentication. Auth methods
are polymorphic ``AbstractKindModel`` subclasses, so the ``auth`` field on
``GrafanaInstance`` is declared with ``KindModelSelectorType`` and the
framework deserializes the stored dict into the right subclass based on
the ``kind`` field.
"""

from __future__ import annotations

from restalchemy.dm import models as ra_models
from restalchemy.dm import properties, types_dynamic
from restalchemy.dm import types as ra_types


class AbstractAuthMethod(
    ra_models.SimpleViewMixin,
    types_dynamic.AbstractKindModel,
):
    """Abstract Grafana authentication method.

    Subclasses implement a specific auth kind (password, oidc, etc.).
    The ``kind`` field is auto-populated by ``AbstractKindModel`` from
    the class' ``KIND`` attribute.
    """


class PasswordAuth(AbstractAuthMethod):
    """Grafana authentication via the built-in admin password.

    Renders ``GF_SECURITY_ADMIN_PASSWORD`` from the ``password`` field.
    """

    KIND = "password"

    password = properties.property(
        ra_types.String(min_length=1, max_length=256), required=True
    )


class OidcAuth(AbstractAuthMethod):
    """Grafana authentication via a generic OAuth/OIDC provider.

    Renders ``GF_AUTH_GENERIC_OAUTH_*`` environment variables. The
    admin password is not delivered by the control plane — it is
    generated by the DP image bootstrap procedure, so all users
    authenticate through OIDC.
    """

    KIND = "oidc"

    client_id = properties.property(
        ra_types.String(min_length=1, max_length=128), required=True
    )
    client_secret = properties.property(
        ra_types.String(min_length=1, max_length=256), required=True
    )
    # OIDC authorization endpoint — browser redirects here for user login.
    auth_url = properties.property(
        ra_types.String(min_length=1, max_length=2048), required=True
    )
    # Token endpoint — Grafana exchanges the auth code for an access token.
    token_url = properties.property(
        ra_types.String(min_length=1, max_length=2048), required=True
    )
    # UserInfo endpoint — Grafana fetches user profile info after token exchange.
    api_url = properties.property(
        ra_types.String(min_length=1, max_length=2048), required=True
    )
    # Public base URL of Grafana (GF_SERVER_ROOT_URL); must match the IAM Idp callback.
    root_url = properties.property(
        ra_types.String(min_length=1, max_length=2048), required=True
    )
    scopes = properties.property(
        ra_types.String(max_length=256), default="openid profile email"
    )
